function current_fish_color --description 'ex: command, quote, ...'
  echo "set fish_color_normal         $fish_color_normal"
  echo "set fish_color_command        $fish_color_command"
  echo "set fish_color_quote          $fish_color_quote"
  echo "set fish_color_redirection    $fish_color_redirection"
  echo "set fish_color_end            $fish_color_end"
  echo "set fish_color_error          $fish_color_error"
  echo "set fish_color_param          $fish_color_param"
  echo "set fish_color_comment        $fish_color_comment"
  echo "set fish_color_match          $fish_color_match"
  echo "set fish_color_search_match   $fish_color_search_match"
  echo "set fish_color_operator       $fish_color_operator"
  echo "set fish_color_escape         $fish_color_escape"
  echo "set fish_color_autosuggestion $fish_color_autosuggestion"
end
